Do not link with libgcc_eh
Linking with libgcc_eh breaks rump_fs, not linking with it breaks
stdcxx (undefined reference to `_Unwind_RaiseException'). This needs
further investigation, reverting for now.

This reverts commit 5f88835e3bba5c5aab0a935f03d699efaed56167.